### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by nickandrew**
I was able to get the program to read the current firmware from my OLS device. While doing so I experienced several problems and made a few improvements.

I still haven't been able to retrieve my FPGA bitstream with this program. That's a later effort.

### CODE REVIEW

**Comment by robots** [comment]
I have had no problem with reading and writing of the firmware. Can you be more specific? Probably different bootloader version?

When does this happen ? "Error reading flash id - OLS id was returned instead"

I am merging those fixes as they seem ok.

**Comment by nickandrew** [comment]
Regarding the "OLS id was returned instead":

I have no idea why it's happening, but I can see it on the strace. The first strace occurs inside OLS_GetID() function:

```
write(3, "\0\0\0\0", 4)                 = 4
read(3, "H\1F\3\0B\2", 7)               = 7
```

The code then calls OLS_GetFlashId():

```
write(3, "\1\0\0\0", 4)                 = 4
read(3, "H\1F\3", 4)                    = 4
```

So sending 0x01, 0x00, 0x00, 0x00 causes the same response as before. And it's repeatable; I put a loop in to try the get flash id a few times, and this was the result:

```
write(3, "\1\0\0\0", 4)                 = 4
read(3, "H\1F\3", 4)                    = 4
write(3, "\1\0\0\0", 4)                 = 4
read(3, "\0B\2", 4)                     = 3
read(3, "H", 1)                         = 1
write(3, "\1\0\0\0", 4)                 = 4
read(3, "\1F\3\0", 4)                   = 4
write(3, "\1\0\0\0", 4)                 = 4
read(3, "B\2", 4)                       = 2
read(3, "H\1", 2)                       = 2
write(3, "\1\0\0\0", 4)                 = 4
read(3, "F\3\0B", 4)                    = 4
```

The previous code tested the 4 bytes returned for a flash id and, when it couldn't find them, printed `Error - unknown flash type (48 01 46 03)` which is misleading; it's not a flash type at all. So I added a test for this particular odd result.

I'm also not the only one getting it. As recently as August 2015:

http://dangerousprototypes.com/forum/viewtopic.php?f=23&t=7364&p=61815&hilit=unknown+flash+type#p61808

And this, from somebody trying to upgrade an OLS currently running FPGA firmware 2.x:

http://dangerousprototypes.com/forum/viewtopic.php?f=23&t=659&start=15#p58354

Even in 2010 somebody experienced this error:

http://dangerousprototypes.com/forum/viewtopic.php?t=659#p6163

I will happily supply a better error message when I have figured out why it is happening :-)

**Comment by nickandrew** [comment]
I have done more testing and I wonder if something is wrong with this particular firmware. The firmware just looks at the first byte (of 4) received to determine what the command is; if the firmware is getting out of sync with ols-fwloader for any reason the firmware will see a 0x00 as the first command byte, not the true one.

To test this, I sent 8 * 0x01 and watched the strace:

```
write(3, "\0\0\0\0", 4)                 = 4            <-- at this point the firmware must be out of sync
read(3, "H\1F\3\0B\2", 7)               = 7
write(3, "\1\1\1\1\1\1\1\1", 8)         = 8
read(3, "H\1F\3\0B\2", 40)              = 7       <-- incorrect response to command starting with 0
read(3, "\3570\23\0", 33)               = 4        <-- correct flash id
read(3, "", 29)                         = 0
```

The firmware is out of sync so it sees 1-3 bytes of the `\0\0\0\0` as the start of the next command, which is why it sends back `H\1F\3` etc. The next write ensures that the firmware sees 0x01 as the command character and so it sends back the flash type bytes.

**Comment by jcw** [comment]
Web search brought me to this page ... many years later. I'm trying to get an OLS working which I purchased ages ago, the pcb says v1.04 - updating the PIC worked, then I got this:

```
[...]/ols-0308/OLS_Upgrader/linbin64$ sudo ./fw_update -e -w -m flash -vid 0x04d8 -pid 0xfc90 -ix ../PIC_firmware/OLSv1.firmware.v3.0.hex
U2IO flash erasing: DONE.
U2IO flash programming: DONE.
RESET Device
Operation successfully completed.
[...]/ols-0308/OLS_Upgrader/linbin64$ sudo ./ols-loader -selftest -p:/dev/ttyACM0
Logic Sniffer ROM loader v0.3 (November 9, 2010)
Opening serial port '/dev/ttyACM0' @ 921600 ... OK
Found OLS HW: 1, FW: 3.0, Boot: 2
Error - unknown flash type (48 01 46 03)
[...]/ols-0308/OLS_Upgrader/linbin64$ sudo ./ols-loader -write -erase -p:/dev/ttyACM0 -wB:FPGAROM/logic_sniffer_3.07-Demon-Core.bit
Logic Sniffer ROM loader v0.3 (November 9, 2010)
Opening serial port '/dev/ttyACM0' @ 921600 ... OK
Found OLS HW: 1, FW: 3.0, Boot: 2
Error - unknown flash type (48 01 46 03)
```

Would be great if I could get this working somehow - my 16-bit logic analyser isn't cutting it for one project I'm investigating, and since the OLS can do 32 lanes, it'd be just the right tool here.

**Comment by jcw** [comment]
Whoops, I think it's all down to my confusion. Using some other instructions, the following worked:

```
$ sudo ols_fwloader -f APP -P /dev/ttyACM0 -W -t BIN -w logic_sniffer_3.07-Demon-Core.bit
Found OLS HW: 1, FW: 3.0, Boot: 2
Found flash: WINBOND W25X40
Reading file 'logic_sniffer_3.07-Demon-Core.bit'
Erasing flash ...
Chip erase ... done :)
Will write 662 pages
.....................
```

My apologies for the noise. I can delete these last two messages if you prefer.

**Pull request merged**
